import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome7widget/generated/GeneratedMenuhamburgerWidget3.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome7widget/generated/GeneratedBeimaginativeWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome7widget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome7widget/generated/GeneratedBeimaginative11Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome7widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget3.dart';

/* Frame home-7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 395.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 67.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget3(),
              ),
              Positioned(
                left: 6.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 408.0,
                height: 41.0,
                child: GeneratedBeimaginativeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 156.0,
                child: GeneratedBeimaginative11Widget(),
              )
            ]),
      ),
    ));
  }
}
