import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplash2widget/generated/GeneratedSplash2Widget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplash2widget/generated/GeneratedSplash1Widget.dart';

/* Frame splash-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplash2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -19.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 549.0,
                height: 842.0,
                child: GeneratedSplash2Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: -8.157501220703125,
                right: null,
                bottom: null,
                width: 446.9412841796875,
                height: 562.063232421875,
                child: GeneratedSplash1Widget(),
              )
            ]),
      ),
    ));
  }
}
