description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.0"
  path_drawing: "^0.4.1+1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-600.ttf"
          style: "normal"
          weight: 600
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
