import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedaboutwidget/generated/GeneratedMenuhamburgerWidget10.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedaboutwidget/generated/GeneratedComponent1Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedaboutwidget/generated/GeneratedCindyWachterLevinebeganalifelongloveofthehealingartswhe.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedaboutwidget/generated/GeneratedAboutAuthorWidget.dart';

/* Frame about
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(181, 255, 192, 202),
                  ),
                ),
                Positioned(
                  left: 396.0,
                  top: 52.0,
                  right: null,
                  bottom: null,
                  width: 48.0,
                  height: 24.0,
                  child: GeneratedMenuhamburgerWidget10(),
                ),
                Positioned(
                  left: 15.0,
                  top: 37.0,
                  right: null,
                  bottom: null,
                  width: 56.47924041748047,
                  height: 36.19181823730469,
                  child: GeneratedComponent1Widget(),
                ),
                Positioned(
                  left: -46.0,
                  top: 93.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 52.0,
                  child: GeneratedAboutAuthorWidget(),
                ),
                Positioned(
                  left: 23.0,
                  top: 179.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 651.0,
                  child:
                      GeneratedCindyWachterLevinebeganalifelongloveofthehealingartswhe(),
                )
              ]),
        ),
      ),
    ));
  }
}
