import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome10widget/generated/GeneratedRectangle1Widget9.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome10widget/generated/GeneratedBetruetoyourselfWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome10widget/generated/GeneratedMenuhamburgerWidget9.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome10widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget9.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome10widget/generated/GeneratedBepositive11Widget1.dart';

/* Frame home-10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 396.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget9(),
              ),
              Positioned(
                left: 31.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget9(),
              ),
              Positioned(
                left: 68.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 422.0,
                height: 143.0,
                child: GeneratedBetruetoyourselfWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 150.0,
                child: GeneratedBepositive11Widget1(),
              )
            ]),
      ),
    ));
  }
}
