import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedpage9widget/generated/GeneratedPage91Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedpage9widget/generated/GeneratedComponent1Widget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedpage9widget/generated/GeneratedMenuhamburgerWidget11.dart';

/* Frame page-9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 396.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget11(),
              ),
              Positioned(
                left: 12.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 56.47924041748047,
                height: 36.19181823730469,
                child: GeneratedComponent1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 583.7465209960938,
                child: GeneratedPage91Widget(),
              )
            ]),
      ),
    ));
  }
}
