import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome3widget/generated/GeneratedMenuhamburgerWidget4.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome3widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome3widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget4.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome3widget/generated/GeneratedBekind1Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome3widget/generated/GeneratedBekind2Widget.dart';

/* Frame home-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 395.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget4(),
              ),
              Positioned(
                left: 31.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 64.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 161.0,
                child: GeneratedBekind1Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 772.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 104.0,
                child: GeneratedBekind2Widget(),
              )
            ]),
      ),
    ));
  }
}
