import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedCovercolorWidget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedFOLLOWYOURHEARTWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedByCindyWatcherLevineWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedButtonPrimaryWidget2.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedsplashwidget/generated/GeneratedLine3Widget1.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 216, 46, 47),
                  ),
                ),
                Positioned(
                  left: -3.0,
                  top: -289.2208557128906,
                  right: null,
                  bottom: null,
                  width: 413.3392028808594,
                  height: 1185.6485595703125,
                  child: GeneratedCovercolorWidget1(),
                ),
                Positioned(
                  left: 27.0,
                  top: 352.0,
                  right: null,
                  bottom: null,
                  width: 366.0,
                  height: 44.0,
                  child: GeneratedFOLLOWYOURHEARTWidget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 319.0,
                  right: null,
                  bottom: null,
                  width: 107.0,
                  height: 4.0,
                  child: GeneratedLine1Widget(),
                ),
                Positioned(
                  left: 395.0,
                  top: 319.0,
                  right: null,
                  bottom: null,
                  width: 107.0,
                  height: 4.0,
                  child: GeneratedLine4Widget1(),
                ),
                Positioned(
                  left: 391.44622802734375,
                  top: 426.0027770996094,
                  right: null,
                  bottom: null,
                  width: 357.44622802734375,
                  height: 0.0013832284603267908,
                  child: GeneratedLine2Widget(),
                ),
                Positioned(
                  left: 387.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 357.0,
                  height: 0.998607873916626,
                  child: GeneratedLine3Widget1(),
                ),
                Positioned(
                  left: 151.0,
                  top: 448.0,
                  right: null,
                  bottom: null,
                  width: 242.0,
                  height: 25.0,
                  child: GeneratedByCindyWatcherLevineWidget(),
                ),
                Positioned(
                  left: 23.0,
                  top: null,
                  right: 27.0,
                  bottom: 221.0,
                  width: null,
                  height: 76.0,
                  child: GeneratedButtonPrimaryWidget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
