import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedMenuitemWidget3.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedMenuitemWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedMenuitemWidget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedMenuitemWidget2.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedUser5121Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedHelloSiddharthaWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedmenudrawerwidget/generated/GeneratedLine11Widget.dart';

/* Frame menu-drawer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenudrawerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 303.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 42.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 220.0,
                child: GeneratedUser5121Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 36.0,
                child: GeneratedHelloSiddharthaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 1.0,
                child: GeneratedLine11Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 65.0,
                child: GeneratedMenuitemWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 65.0,
                child: GeneratedMenuitemWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 65.0,
                child: GeneratedMenuitemWidget2(),
              ),
              Positioned(
                left: 13.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 65.0,
                child: GeneratedMenuitemWidget3(),
              )
            ]),
      ),
    ));
  }
}
