import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedloginwidget/generated/GeneratedPageHeaderWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedloginwidget/generated/GeneratedButtonPrimaryWidget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedloginwidget/generated/GeneratedInputTextWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedloginwidget/generated/GeneratedForgotyourpasswordWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedloginwidget/generated/GeneratedInputTextWidget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedloginwidget/generated/GeneratedCovercolorWidget.dart';

/* Frame login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 216, 46, 47),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -289.2208557128906,
                right: null,
                bottom: null,
                width: 413.3392028808594,
                height: 1185.6485595703125,
                child: GeneratedCovercolorWidget(),
              ),
              Positioned(
                left: 23.0,
                top: null,
                right: 23.0,
                bottom: 221.0,
                width: null,
                height: 76.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 430.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 158.0,
                width: 269.0,
                height: 31.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotyourpasswordWidget()),
              ),
              Positioned(
                left: 35.0,
                top: 337.0,
                right: 36.0,
                bottom: null,
                width: null,
                height: 61.0,
                child: GeneratedInputTextWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 448.0,
                right: 37.0,
                bottom: null,
                width: null,
                height: 61.0,
                child: GeneratedInputTextWidget1(),
              )
            ]),
      ),
    ));
  }
}
