import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome4widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget7.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome4widget/generated/GeneratedMenuhamburgerWidget7.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome4widget/generated/GeneratedConfidentWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome4widget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome4widget/generated/GeneratedBeconfident1Widget.dart';

/* Frame home-4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 396.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget7(),
              ),
              Positioned(
                left: 31.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget7(),
              ),
              Positioned(
                left: 68.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget7(),
              ),
              Positioned(
                left: -6.0,
                top: 833.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 50.442474365234375,
                child: GeneratedConfidentWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 164.84210205078125,
                child: GeneratedBeconfident1Widget(),
              )
            ]),
      ),
    ));
  }
}
