import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome8widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget5.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome8widget/generated/GeneratedBekind1Widget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome8widget/generated/GeneratedBegoodtoyourselfWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome8widget/generated/GeneratedMenuhamburgerWidget5.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome8widget/generated/GeneratedRectangle1Widget5.dart';

/* Frame home-8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 395.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget5(),
              ),
              Positioned(
                left: 31.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 64.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 161.0,
                child: GeneratedBekind1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 753.0,
                right: null,
                bottom: null,
                width: 423.0,
                height: 129.0,
                child: GeneratedBegoodtoyourselfWidget(),
              )
            ]),
      ),
    ));
  }
}
