import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome5widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget8.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome5widget/generated/GeneratedBegratefulWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome5widget/generated/GeneratedRectangle1Widget8.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome5widget/generated/GeneratedMenuhamburgerWidget8.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome5widget/generated/GeneratedBepositive12Widget.dart';

/* Frame home-5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 396.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget8(),
              ),
              Positioned(
                left: 31.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget8(),
              ),
              Positioned(
                left: 68.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 150.0,
                child: GeneratedBepositive12Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 47.0,
                child: GeneratedBegratefulWidget(),
              )
            ]),
      ),
    ));
  }
}
