import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome6widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome6widget/generated/GeneratedMenuhamburgerWidget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome6widget/generated/GeneratedBeinspiredWidget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome6widget/generated/GeneratedHappyThoughtsCreateHappyFeelingsWidget1.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedhome6widget/generated/GeneratedBepositive1Widget1.dart';

/* Frame home-6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 395.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 380.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 67.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 207.3333282470703,
                child: GeneratedHappyThoughtsCreateHappyFeelingsWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 127.0,
                child: GeneratedBepositive1Widget1(),
              ),
              Positioned(
                left: -8.0,
                top: 822.0,
                right: null,
                bottom: null,
                width: 422.0,
                height: 64.0,
                child: GeneratedBeinspiredWidget(),
              )
            ]),
      ),
    ));
  }
}
