import 'package:flutter/material.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedpage53widget/generated/GeneratedMenuhamburgerWidget12.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedpage53widget/generated/GeneratedPage531Widget.dart';
import 'package:flutterapp/book_20quotes_20appapp/generatedpage53widget/generated/GeneratedComponent1Widget2.dart';

/* Frame page-53
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPage53Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 396.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedMenuhamburgerWidget12(),
              ),
              Positioned(
                left: 12.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 56.47924041748047,
                height: 36.19181823730469,
                child: GeneratedComponent1Widget2(),
              ),
              Positioned(
                left: -20.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 471.0,
                height: 555.0,
                child: GeneratedPage531Widget(),
              )
            ]),
      ),
    ));
  }
}
